---
# tasks file for ec2-role
- name: Creating EC2 Instance
  amazon.aws.ec2_instance:
    name: "{{ item.name }}"
    key_name: "pallab-aws-keypair"
    #vpc_subnet_id: subnet-5ca1ab1e
    instance_type: "{{ type }}"
    security_group: default
    region: us-east-1
    aws_access_key: '{{aws_access_key}}' # from vault
    aws_secret_key: '{{aws_secret_key}}' # from vault
    network:
      assign_public_ip: true
    image_id: "{{ item.image }}"
    tags:
      Environment: "{{ item.name }}"
  loop: 
  - {image: "ami-04a81a99f5ec58529" , name: "instance-1"}
  - {image: "ami-04a81a99f5ec58529" , name: "instance-2"}
  - {image: "ami-0ba9883b710b05ac6" , name: "instance-3"}