---
- name: play-1
  hosts: localhost
  gather_facts: yes
  tasks:
    - name: print date
      ansible.builtin.command: date
      register: date_output

    - name: print date_output
      debug:
        var: date_output.stdout

    # - name: Print Ansible facts
    #   debug:
    #     var: ansible_facts
    - name: Print OS details
      debug:
        msg: "This server is running {{ ansible_distribution }} {{ ansible_distribution_version }} and the OS family is {{ ansible_os_family }}"

    - name: print message
      debug:
        msg: "Condition Example!"
      when: ansible_facts['os_family'] == 'Darwin'

    # - name: Get available disk space
    #   command: df -h / | awk 'NR==2 {print $4}'
    #   register: disk_space

    # - name: Print disk space
    #   debug:
    #     msg: "Available disk space: {{ disk_space.stdout }}"

    # - name: Alert if disk space is below 5GB
    #   debug:
    #     msg: "Warning! Low disk space: {{ disk_space.stdout }}"
    #   when: disk_space.stdout is version('5G', '<')




# - name: play-2
#   hosts: localhost
#   gather_facts: no
#   tasks:
#     - name: Print Play 2
#       ansible.builtin.debug:
#         msg: "Play 2!"

#     - name: python version
#       ansible.builtin.command: python3 --version
#       register: python_version

#     - name: print python version  output
#       ansible.builtin.debug:
#         var: python_version.stdout

#     - name: print ansible version  output
#       ansible.builtin.debug:
#         var: ansible_version.full

#     - name: print ansible version  output
#       ansible.builtin.debug:
#         var: ansible_version.major

    # - name: Ensure pip is installed
    #   easy_install:
    #     name: pip

    # - name: Install ansible-lint
    #   pip:
    #     name: ansible-lint

    # - name: Run ansible-lint
    #   command: ansible-lint /Users/pallabpanda/LearnAndProjects/ansibleplaybook-1y/myplaybook.yml