---
- hosts: all
  become: true
  tasks:
  - name: print all ansible gather fatcs
    ansible.builtin.debug:
      var: ansible_fatcs
  - name: shutdiwn ubuntu ec2 instance
    ansible.builtin.command: /sbin/shutdown -t now
    when:
      ansible_fatcs['os_family'] == 'Debian'